// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    // Test name: Untitled
    // Step # | name | target | value
    // 1 | open | /all-reports-derivatives | 
    driver.get("https://www.nseindia.com/all-reports-derivatives");
    // 2 | setWindowSize | 1050x708 | 
    driver.manage().window().setSize(new Dimension(1050, 708));
    // 3 | click | linkText=Archives | 
    driver.findElement(By.linkText("Archives")).click();
    // 4 | click | id=cr_deriv_equity_archives_date | 
    driver.findElement(By.id("cr_deriv_equity_archives_date")).click();
    // 5 | click | css=.gj-picker > div > div > div:nth-child(1) | 
    driver.findElement(By.cssSelector(".gj-picker > div > div > div:nth-child(1)")).click();
    // 6 | click | css=.gj-picker > div > div > div:nth-child(1) | 
    driver.findElement(By.cssSelector(".gj-picker > div > div > div:nth-child(1)")).click();
    // 7 | click | css=tr:nth-child(2) > .current-month:nth-child(2) > div | 
    driver.findElement(By.cssSelector("tr:nth-child(2) > .current-month:nth-child(2) > div")).click();
    // 8 | click | css=#cr_deriv_equity_archives .col-lg-4:nth-child(9) .pdf-download-link | 
    driver.findElement(By.cssSelector("#cr_deriv_equity_archives .col-lg-4:nth-child(9) .pdf-download-link")).click();
    // 9 | mouseOver | css=#cr_deriv_equity_archives .col-lg-4:nth-child(9) .pdf-download-link | 
    {
      WebElement element = driver.findElement(By.cssSelector("#cr_deriv_equity_archives .col-lg-4:nth-child(9) .pdf-download-link"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | mouseOut | css=#cr_deriv_equity_archives .col-lg-4:nth-child(9) .pdf-download-link | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
